server:
  port: 0

spring:
  application:
    name: operis-task-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URI:http://localhost:8888}
  cloud:
    config:
      enabled: true

rabbitmq:
  exchange:
    name: task-exchange
  queue:
    cta-service: task.cta.queue
  routing-key:
    new: task.new
    accept: task.accept
    reject: task.reject


