server:
  port: 0

spring:
  application:
    name: operis-project-service
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    config:
      enabled: true

logging:
  file:
    name: logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

rabbitmq:
  exchange:
    name: project.invitation.exchange
  queue:
    notification-service: project.invitation.notification.queue
    cta-service: project.invitation.cta.queue
  routing:
    new: project.invite
    accept: project.invitation.accept
    reject: project.invitation.reject